#version: '3.13'
networks:
  reverse-proxy:
    external: true

services:
  edi-forecast:
    build: .
    container_name: edi_forecast_app
    volumes:
      # Monta la cartella data dell'host nella cartella data del container
      - ./src/data:/edi_forecast_app/src/data
      # Opzionale: monta anche logs se vuoi mantenerli persistenti
      - ./logs:/edi_forecast_app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Rome
    env_file:
      - .env
    networks:
      - reverse-proxy
      - default    
    ports:
      - "8501:8501"      
    restart: unless-stopped

    